### ISSUE TITLE
Rxjs does have operators targetting ending

### ISSUE THREAD

**Issue by brucou** [ivan-kleshnin/reactive-polyglot#6]
Reacting to this : 

> RxJS
> 
>   Three primitives: Observer, Observable, Subject.
>   Observables end on error.
>   Provides API to handle errors.
>   Does not provide API to handle ending.

Rxjs v4 does allow to do any kind of operation on the message received/passed through the operators `materialize`/`dematerialize`. As often the case, those operators are poorly documented, but are very useful for library creators, or custom error/completion management. Basically there are three types of notifications : next, error, complete (no surprise right?), and when you dematerialize, you receive those messages without the associated side-effects. When you finish doing what you want with them (modifying, replacing, intercepting), you can materialize behind, and your stream continues as usual. 

Then you also have the `finally` operators, and `doOnCompleted` I believe in v4 too. I don't know enough of v5 to talk about it. And of course the `concat` operator, as you mentioned for `xstream`.

**Comment by ivan-kleshnin** [comment]
Hi. Thank you for the comment.

> Rxjs v4 does allow to do any kind of operation on the message received/passed through the operators materialize/dematerialize

I don't see relations between those operators and `onCompleted` event, honestly.

I also believe side effects should be moved outside of the app code as CycleJS promotes.
`materialize` / `dematerialize` look like a dark magic one should avoid.

> Then you also have the finally operators, and doOnCompleted I believe in v4 too. I don't know enough of v5 to talk about it. And of course the concat operator, as you mentioned for xstream.

Agreed. I'm going to correct corresponding text in the README.

**Comment by brucou** [comment]
Doc : 
- https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/materialize.md
- http://reactivex.io/documentation/operators/materialize-dematerialize.html

Examples of use:
- http://stackoverflow.com/questions/31999682/receiving-done-notifications-from-observables-built-using-switch/32001230#32001230
- http://stackoverflow.com/questions/37649462/whats-the-use-case-of-notification-in-rxjs/37649579#37649579

This is a bit out of the subject, but the goal of the app being to perform side-effects, it is hard to see how those side-effects are going to be out of the app. What you probably mean is that you should try to separate functions with side-effects and those without. Then in `CycleJs`, remember that in the `main` loop there is a bunch of side-effects being performed (in general `read` effects, but they count as effects just like any other). It is surprising that you would contend that they have been moved somehow outside the app.

**Comment by ivan-kleshnin** [comment]
> This is a bit out of the subject, but the goal of the app being to perform side-effects, it is hard to see how those side-effects are going to be out of the app. ... It is surprising that you would contend that they have been moved somehow outside the app.

In CycleJS app only initiates effects. Then they occur in library code which I don't consider a part of application. I think we both properly understand how it goes so it's just different angles of view applied.

**Comment by brucou** [comment]
Alright I understand one of your points. But still, even in you don't consider drivers to be part of the app, you are still doing read effects in your main. Then `materialize` and `dematerialize` should not be producing more side-effects than `catch` or `map`. They are operators just like any other, and I would argue that they are pure functions. Whatever source you throw at them, they will always returns the same sink (depending how you define equality for two observables of course).
Not trying to be picky or anything, but I hear a lot about purity of cyclejs main, when I suppose what is meant is no write-effect. And the final verdict on purity should depend anyways on how you define equality for two observables.

**Comment by ivan-kleshnin** [comment]
> Not trying to be picky or anything, but I hear a lot about purity of cyclejs main, when I suppose what is meant is no write-effect. 

No imperative read actions as well! _(the "effect" word is not used in CycleJS)_.
The simplest CycleJS app can contain 0 imperative actions (meaning no explicit reads or writes). When it comes to real-world... it's more complicated.

**Comment by ivan-kleshnin** [comment]
And what do you mean by read effect in RxJS in general?
Write effect is `subj.next()`. Read effect is _?

An appropriate example for read effect would be [flyd.get](https://github.com/paldepind/flyd) but this library differs fundamentally from RxJS being about reactive properties rather than reactive streams. Properties contain publicly accessible state, hence imperative reading is possible.

`.subscribe` is a side effect but it does not affect external world so it does not count.
_Just like every function takes time to evaluate and persists in stack but we do not think it breaks purity (because effects are enclosed)._

**Comment by brucou** [comment]
Sorry it took me so long to answer. In short:
- a pure function is a function which:
  1 Evaluation of the result does not cause any **semantically observable** side effect or output  
  2 produce the same output for the same input

In cyclejs, supposing a main function which use the DOM 'source', for example `DOM.select...` that function performs a side-effect, a read effect, or side-cause whichever way you want to call it. The fact is it reads from the external world. And this is a semantically observable side-effect (point 1). The fact that it initiates x and that x is somewhere else in a driver does not change a thing. You can't eliminate side-effects by saying that they happen in a library, otherwise we could move them all to a different file and call all our functions side-effect free. We could write to a database through a database library, and still pretend that our function is pure. That is not the case.

Second point:
- as you know sometimes you have to use `isolate` in cyclejs precisely because your read effect could return different values for the same call. Meaning that `DOM.select` IS an impure function (because of point 2). There is no way you are going to use an impure function in your function and it is going to remain pure. 

So `DOM.select` infringes both contracts for a pure function and whatever function which uses it also does.

Which brings me to my point that saying that, drivers aside, a cyclejs app is a pure function is not accurate, whichever way you look at it.

**Comment by ivan-kleshnin** [comment]
@brucou your counter-arguments are reasonable, so I have to change my mind.
Thanks for taking time to address this and detailed answers!
